Основы JS. Примитивные типы данных
js-tasks-ru/js-20201211_nikson-k pull request #2
Opened 2020-12-16 11:30 UTC by Kilovatiy

2020-12-16 11:55 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-17 22:55 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
пожалуйста проверьте объявления переменных. Через `const` должны быть объявлены переменные которые не будут изменяться далее по коду

2020-12-17 22:56 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortedArray.reverse();
попробуйте избавиться от `reverse` и сортировать данные сразу в нужном порядке

2020-12-17 22:57 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (field in obj) {
оператор `in` крайне редко используется на практике при проверки наличия свойства в объекте, но это мы обсудим уже на следующем занятии.

2020-12-17 22:58 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  while(++i < fields.length) {
`fields` - это массив, а у массивов уже есть встроенные методы для итерации, поэтому следует отдавать им предпочтение и избегать `while, for` циклов

2020-12-17 22:59 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +      delete obj[field];
`delete` крайне нежелательно применять на объектах. Подробнее обсудим на след. занятии

2020-12-17 22:59 UTC, dosandk requested changes
необходимо избавиться от `reverse` в решении `sortStrings`

2020-12-18 07:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-18 14:51 UTC, dosandk approved these changes

2020-12-18 14:51 UTC, merged